# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171226_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
